openapi: 3.0.3
x-stoplight:
  id: q0pbqzd9uictu
info:
  title: Harness NextGen Software Delivery Platform API Reference
  version: '1.0'
  description: This is the Open Api Spec 3 for the IDP Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
  contact:
    name: API Support
    email: contact@harness.io
    url: 'https://harness.io/'
servers:
  - url: 'https://app.harness.io'
paths:
  /v1/backstage-env-variables:
    get:
      summary: List Backstage Env Variables
      responses:
        '200':
          $ref: '#/components/responses/BackstageEnvVariableResponseList'
      operationId: get-backstage-env-variables
      description: Get all backsage env variables mapping for a given account
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
      security:
        - x-api-key: []
      x-internal: true
      tags:
        - BackstageEnvVariable
    post:
      summary: Create Backstage Environment Variable
      operationId: create-backstage-env-variable
      responses:
        '201':
          $ref: '#/components/responses/BackstageEnvVariableResponse'
      description: Creates an backstage environment variable
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/BackstageEnvVariableRequest'
      x-internal: true
      tags:
        - BackstageEnvVariable
  /v1/backstage-env-variables/sync:
    put:
      summary: Sync Backstage Environment Variables
      operationId: sync-backstage-env-variables
      description: Synchronize all backstage environment variables mapping for a given account
      x-internal: true
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      responses:
        '204':
          description: No Content
      tags:
        - BackstageEnvVariable
  '/v1/backstage-env-variables/{backstage-env-variable}':
    parameters:
      - $ref: '#/components/parameters/BackstageEnvVariable'
    get:
      summary: Get Backstage Environment Variable
      responses:
        '200':
          $ref: '#/components/responses/BackstageEnvVariableResponse'
      operationId: get-backstage-env-variable
      description: Get backstage environment variable mapping for a given backstage env variable
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      tags:
        - BackstageEnvVariable
    put:
      summary: Updates a backstage env variable
      operationId: update-backstage-env-variable
      responses:
        '200':
          $ref: '#/components/responses/BackstageEnvVariableResponse'
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/BackstageEnvVariableRequest'
      description: Updates the specified backstage env variable
      x-internal: true
      tags:
        - BackstageEnvVariable
    delete:
      summary: Deletes a backstage env variable
      operationId: delete-backstage-env-variable
      description: Deletes the requested backstage env variable
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      responses:
        '204':
          description: No Content
      tags:
        - BackstageEnvVariable
  /v1/backstage-env-variables/batch:
    post:
      summary: Creates Multiple backstage env variables
      operationId: create-backstage-env-variables
      responses:
        '201':
          $ref: '#/components/responses/BackstageEnvVariableResponseList'
      description: Creates multiple backstage env variables
      x-internal: true
      requestBody:
        $ref: '#/components/requestBodies/BackstageEnvVariableBatchRequest'
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      tags:
        - BackstageEnvVariable
    put:
      summary: Updates Multiple backstage env variables
      operationId: update-backstage-env-variables
      responses:
        '200':
          $ref: '#/components/responses/BackstageEnvVariableResponseList'
      description: Updates the multiple backstage env variables specified in the request
      x-internal: true
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/BackstageEnvVariableBatchRequest'
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - BackstageEnvVariable
    delete:
      summary: Deletes Multiple backstage env variables
      operationId: delete-backstage-env-variables
      responses:
        '204':
          description: No Content
      description: Deletes the multiple backstage env variables specified in the request
      x-internal: true
      security:
        - x-api-key: []
      parameters:
        - schema:
            type: array
            items:
              type: string
          in: query
          name: backstage-env-variable
          description: Identifier field of backstage env variable
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - BackstageEnvVariable
  /v1/backstage-permissions:
    get:
      summary: Get Backstage Permissions
      responses:
        '200':
          $ref: '#/components/responses/BackstagePermissionsResponse'
      operationId: get-backstage-permissions
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      description: Get all backstage permissions for a given account
      security:
        - x-api-key: []
      x-internal: true
      tags:
        - BackstagePermissions
    post:
      summary: Create backstage Permissions
      operationId: create-backstage-permissions
      responses:
        '201':
          $ref: '#/components/responses/BackstagePermissionsResponse'
      description: Creates backstage Permissions for a given account
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/BackstagePermissionsRequest'
      x-internal: true
      tags:
        - BackstagePermissions
    put:
      summary: Updates Backstage Permission
      operationId: update-backstage-permissions
      responses:
        '200':
          $ref: '#/components/responses/BackstagePermissionsResponse'
      description: Update Backstage Permission
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      requestBody:
        $ref: '#/components/requestBodies/BackstagePermissionsRequest'
      tags:
        - BackstagePermissions
  '/v1/status-info/{type}':
    parameters:
      - $ref: '#/components/parameters/StatusType'
    get:
      summary: Gets Status Info by type
      tags:
        - StatusInfo
      operationId: get-status-info-by-type
      description: Get status info for the given type
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      responses:
        '200':
          $ref: '#/components/responses/StatusInfoResponse'
      x-internal: true
    post:
      summary: Saves Status Info by type
      tags:
        - StatusInfo
      operationId: save-status-info-by-type
      responses:
        '201':
          $ref: '#/components/responses/StatusInfoResponse'
      description: Saves status info for the given type
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/StatusInfoRequest'
      x-internal: true
  /v1/namespace-info:
    get:
      summary: Get Namespace Info
      responses:
        '200':
          $ref: '#/components/responses/NamespaceResponse'
      operationId: get-namespace-info
      description: Get the corresponding customer namepsace using account id.
      x-internal: true
      security:
        - x-api-key: []
      tags:
        - Namespace
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
    post:
      summary: Create Namespace
      operationId: create-namespace
      description: Create Namespace from accountId
      security:
        - x-api-key: []
      x-internal: true
      responses:
        '200':
          $ref: '#/components/responses/NamespaceResponse'
      tags:
        - Namespace
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
  '/v1/account-info/{namespace}':
    get:
      summary: Get Account Info
      responses:
        '200':
          $ref: '#/components/responses/NamespaceResponse'
      operationId: get-account-for-namespace
      description: Get account information for given namespace
      security:
        - x-api-key: []
      tags:
        - AccountInfo
      x-internal: true
    parameters:
      - schema:
          type: string
        name: namespace
        description: Backstage Namespace
        in: path
        required: true
  /v1/provision-idp:
    post:
      summary: Provision IDP
      operationId: provision-idp
      responses:
        '200':
          $ref: '#/components/responses/NamespaceResponse'
      tags:
        - Provision
      description: Provision IDP for given account
      security:
        - x-api-key: []
      x-internal: true
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
  /v1/onboarding/harness-entities:
    get:
      summary: Get Harness Entities
      operationId: get-harness-entities
      responses:
        '200':
          $ref: '#/components/responses/HarnessEntitiesResponse'
      tags:
        - OnboardingResource
      x-internal: true
      description: Get Harness Entities
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Order'
        - $ref: '#/components/parameters/SearchTerm'
        - schema:
            type: string
          in: query
          name: project_to_filter
          description: This would be used to filter resources having attributes matching the project filter.
  /v1/onboarding/harness-entities-count:
    get:
      summary: Get Harness Entities Count
      operationId: get-harness-entities-count
      responses:
        '200':
          $ref: '#/components/responses/HarnessEntitiesCountResponse'
      description: Get Harness Entities Count
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - OnboardingResource
      x-internal: true
  /v1/onboarding/import-harness-entities:
    post:
      summary: Import Harness Entities to IDP
      operationId: import-harness-entities
      description: Import Harness Entities to IDP
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/ImportHarnessEntitiesRequest'
      tags:
        - OnboardingResource
      responses:
        '200':
          $ref: '#/components/responses/ImportEntitiesResponse'
      x-internal: true
  /v1/onboarding/manual-import:
    post:
      summary: Manually import entity to IDP
      operationId: manual-import-entity
      description: Manually import entity to IDP
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/ManualImportEntityRequest'
      tags:
        - OnboardingResource
      responses:
        '200':
          $ref: '#/components/responses/ImportEntitiesResponse'
      x-internal: true
  /v1/layout:
    get:
      summary: List Layouts
      responses:
        '200':
          $ref: '#/components/responses/LayoutResponse'
      operationId: get-all-layouts
      x-internal: true
      description: Get all layouts
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - LayoutProxy
    post:
      summary: Create layout
      operationId: create-layout
      responses:
        '200':
          $ref: '#/components/responses/LayoutResponse'
      description: Create layout
      x-internal: true
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - LayoutProxy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LayoutRequest'
    delete:
      summary: Delete layout
      operationId: delete-layout
      responses:
        '204':
          description: No Content
      description: Delete layout
      x-internal: true
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - LayoutProxy
      requestBody:
        $ref: '#/components/requestBodies/LayoutRequest'
  '/v1/layout/{layout-identifier}':
    get:
      summary: Get layout
      responses:
        '200':
          $ref: '#/components/responses/LayoutResponse'
      operationId: get-layout
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - LayoutProxy
      description: Get Layout
      x-internal: true
    parameters:
      - $ref: '#/components/parameters/LayoutIdentifier'
  /v1/layout/health:
    get:
      summary: Get Layout Health
      responses:
        '200':
          $ref: '#/components/responses/LayoutResponse'
      operationId: get-layout-health
      description: Get Layout Health
      x-internal: true
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      tags:
        - LayoutProxy
  '/v1/plugin-toggle/{plugin-id}':
    post:
      summary: Toggle Plugin
      operationId: toggle-plugin-for-account
      description: Toggle Backstage Plugin
      responses:
        '200':
          $ref: '#/components/responses/AppConfigResponse'
      parameters:
        - schema:
            type: string
          in: header
          name: Harness-Account
          description: 'Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.'
        - $ref: '#/components/parameters/Enabled'
      security:
        - x-api-key: []
      tags:
        - AppConfig
      x-internal: true
    parameters:
      - schema:
          type: string
        name: plugin-id
        description: Plugin Identifier
        in: path
        required: true
  /v1/plugins-info:
    get:
      summary: List Available Plugins
      tags:
        - PluginInfo
      responses:
        '200':
          $ref: '#/components/responses/PluginInfoResponseList'
      operationId: get-plugins
      description: Get all plugins available
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
  '/v1/plugins-info/{plugin-id}':
    get:
      summary: Get Plugin
      tags:
        - PluginInfo
      responses:
        '200':
          $ref: '#/components/responses/PluginDetailedInfoResponse'
      operationId: get-plugins-info-plugin-id
      description: Get plugin details for given pluginId
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/PluginId'
      x-internal: true
  /v1/app-config:
    post:
      summary: Save Or Update Plugin Config
      operationId: save-or-update-plugin-app-config
      description: Save or Update Plugin Config
      responses:
        '200':
          $ref: '#/components/responses/AppConfigResponse'
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/AppConfigRequest'
      x-internal: true
      tags:
        - AppConfig
  /v1/connectors-info:
    get:
      summary: List Connectors Info
      tags:
        - ConnectorInfo
      responses:
        '200':
          $ref: '#/components/responses/ConnectorInfoResponseList'
      operationId: get-connectors-info
      description: Get all connectors info
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
  /v1/connector-info:
    get:
      summary: 'Get Connector Info'
      tags:
        - ConnectorInfo
      operationId: get-connector-info
      responses:
        '200':
          $ref: '#/components/responses/ConnectorInfoResponse'
      description: Get Connector Info
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
    post:
      summary: Create or Update Connector Info
      tags:
        - ConnectorInfo
      operationId: save-connector-info
      responses:
        '201':
          $ref: '#/components/responses/ConnectorInfoResponse'
      description: Create or update connector info
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      security:
        - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/ConnectorInfoRequest'
      x-internal: true
  '/v1/connector-info/{provider-type}':
    get:
      summary: Get Connector Info by Provider Type
      tags:
        - ConnectorInfo
      responses:
        '200':
          $ref: '#/components/responses/ConnectorInfoResponse'
      operationId: get-connector-info-by-providerType
      description: Get connector info by connector provider type
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/ProviderType'
      x-internal: true
  /v1/merged-plugins-config:
    get:
      summary: Retrieve Merged Config for Enabled Plugins.
      responses:
        '200':
          $ref: '#/components/responses/MergedPluginConfigResponse'
      operationId: get-merged-plugins-config
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      description: API for retriving merged configs for enabled plugin of account.
      tags:
        - MergedPluginsConfig
  /v1/backstage-plugins-info:
    get:
      summary: List Available Backstage Plugins
      tags:
        - PluginInfo
      responses:
        '200':
          $ref: '#/components/responses/PluginInfoResponseList'
      operationId: get-backstage-plugins
      description: Get all backstage plugins available
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
  /v1/plugin/request:
    post:
      summary: Request for a Plugin
      operationId: post-plugin-request
      responses:
        '201':
          description: Created
      tags:
        - PluginInfo
      description: Request for a Plugin
      x-internal: true
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/RequestPluginRequest'
    get:
      summary: Get all plugin requests for an account
      operationId: get-plugin-request
      responses:
        '200':
          $ref: '#/components/responses/PluginRequestResponseList'
      tags:
        - PluginInfo
      x-internal: true
      description: Get all plugin requests for an account
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/Limit'
  /v1/layout/ingest:
    post:
      summary: Ingest plugin layout
      operationId: layout-ingest
      responses:
        '200':
          description: OK
      tags:
        - LayoutProxy
      description: Ingest plugin layout
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LayoutIngestRequest'
  /v1/sync-app-config:
    put:
      summary: Sync merged app-config for a given account
      operationId: sync-app-config
      responses:
        '204':
          description: No Content
      description: API to sync app-config for a given account. This API can be accessed by Support User only.
      x-internal: true
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
        - schema:
            type: boolean
          in: query
          name: base_config
          description: Set true to sync base app-config too
      tags:
        - MergedPluginsConfig
components:
  schemas:
    BackstageEnvVariable:
      title: BackstageEnvVariable
      x-stoplight:
        id: mx4577z6q5ui0
      type: object
      description: Backstage Env Variable
      discriminator:
        propertyName: type
        mapping:
          Config: '#/components/schemas/BackstageEnvConfigVariable'
          Secret: '#/components/schemas/BackstageEnvSecretVariable'
      x-examples: {}
      properties:
        identifier:
          type: string
          x-stoplight:
            id: ifbqbz1jlv275
        env_name:
          type: string
          x-stoplight:
            id: 4zuc9epeyht73
        created:
          type: integer
          x-stoplight:
            id: 77v995uneakvt
          format: int64
        updated:
          type: integer
          x-stoplight:
            id: pj181njip2pmz
          format: int64
        type:
          type: string
          x-stoplight:
            id: sjviqf7m7oeff
            type: null
          description: This specifies the type of backstage env variable
          enum:
            - Config
            - Secret
      required:
        - env_name
        - type
    BackstageEnvSecretVariable:
      title: BackstageEnvSecretVariable
      x-stoplight:
        id: vnn39er7ngivm
      x-discriminator-value: Secret
      allOf:
        - $ref: '#/components/schemas/BackstageEnvVariable'
          x-stoplight:
            id: hf1o5948xcd93
        - type: object
          properties:
            type:
              type: string
              enum:
                - Secret
            harness_secret_identifier:
              type: string
              x-stoplight:
                id: pu8uqht14yg13
          required:
            - type
            - harness_secret_identifier
      x-examples: {}
    BackstageEnvConfigVariable:
      title: BackstageEnvConfigVariable
      x-stoplight:
        id: 070pc2aob4jhc
      x-discriminator-value: Config
      allOf:
        - $ref: '#/components/schemas/BackstageEnvVariable'
          x-stoplight:
            id: roe9dk8ktccbi
        - type: object
          properties:
            type:
              type: string
              enum:
                - Config
            value:
              type: string
              x-stoplight:
                id: 5juxk5r0hnhr5
          required:
            - type
            - value
      x-examples: {}
    BackstageEnvVariableRequest:
      x-stoplight:
        id: a94746e067851
      type: object
      properties:
        env_variable:
          $ref: '#/components/schemas/BackstageEnvVariable'
          x-stoplight:
            id: r2xgjoclqancb
    BackstageEnvVariableBatchRequest:
      type: object
      x-stoplight:
        id: m9tpxiklbpfzk
      properties:
        env_variables:
          x-stoplight:
            id: r2xgjoclqancb
          type: array
          items:
            $ref: '#/components/schemas/BackstageEnvVariable'
            x-stoplight:
              id: i9tsq5o4dan8z
    BackstageEnvVariableResponse:
      x-stoplight:
        id: e8875709fc5b1
      type: object
      properties:
        env_variable:
          $ref: '#/components/schemas/BackstageEnvVariable'
          x-stoplight:
            id: h1ub7r23fswfs
    BackstagePermissions:
      title: BackstagePermissions
      x-stoplight:
        id: mc6dey4g3grx5
      type: object
      properties:
        identifer:
          type: string
        permissions:
          type: array
          items:
            type: string
        user_group:
          type: string
        created:
          type: integer
          format: int64
        updated:
          type: integer
          format: int64
    BackstagePermissionsRequest:
      title: BackstagePermissionsRequest
      x-stoplight:
        id: ixq59j5xh1mr3
      type: object
      properties:
        data:
          $ref: '#/components/schemas/BackstagePermissions'
    BackstagePermissionsResponse:
      title: BackstagePermissionsResponse
      x-stoplight:
        id: iy9wq68joydm6
      type: object
      properties:
        data:
          $ref: '#/components/schemas/BackstagePermissions'
    StatusInfo:
      title: StatusInfo
      x-stoplight:
        id: ae1f1702dd443
      type: object
      properties:
        current_status:
          type: string
          enum:
            - COMPLETED
            - RUNNING
            - PENDING
            - FAILED
            - NOT_FOUND
          x-stoplight:
            id: qq4g9e4sf19tc
        reason:
          type: string
        updated_at:
          type: integer
          format: int64
          x-stoplight:
            id: fsj3mx8ld952o
    StatusInfoResponse:
      title: StatusInfoResponse
      x-stoplight:
        id: d5b32dc406018
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusInfo'
    StatusInfoRequest:
      title: StatusInfoRequest
      x-stoplight:
        id: m2r87gp8mfed7
      type: object
      properties:
        status:
          $ref: '#/components/schemas/StatusInfo'
    NamespaceInfo:
      title: NamespaceInfo
      x-stoplight:
        id: 8ba4gj00yfwre
      type: object
      description: Namespace response body content
      properties:
        account_identifier:
          type: string
          x-stoplight:
            id: f1hxp57bn8wis
        namespace:
          type: string
    NamespaceResponse:
      $ref: '#/components/schemas/NamespaceInfo'
      x-stoplight:
        id: 06dd99ce217ed
      description: Namespace response body
    ImportHarnessEntitiesRequest:
      title: ImportHarnessEntitiesRequest
      x-stoplight:
        id: amr368rxqugif
      type: object
      x-examples: {}
      description: Details of Harness Entities and Catalog Location info
      properties:
        catalog_connector_info:
          $ref: '#/components/schemas/CatalogConnectorInfo'
          x-stoplight:
            id: 2dpge46q45sn2
        entities:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/EntitiesForImport'
        all_import:
          type: boolean
          x-stoplight:
            id: dsm3fnlholwsp
      required:
        - catalog_connector_info
        - entities
    CatalogConnectorInfo:
      title: CatalogConnectorInfo
      x-stoplight:
        id: k72jbjtz6j5jh
      type: object
      description: Details of IDP catalog connector
      properties:
        source_connector:
          $ref: '#/components/schemas/ConnectorDetails'
          x-stoplight:
            id: 218l3eejs3pvn
        repo:
          type: string
        branch:
          type: string
        path:
          type: string
        infra_connector:
          $ref: '#/components/schemas/ConnectorDetails'
          x-stoplight:
            id: y4jr5csvofm3c
      required:
        - source_connector
        - repo
        - branch
        - path
        - infra_connector
    HarnessEntitiesCountResponse:
      title: HarnessEntitiesCountResponse
      x-stoplight:
        id: ijtq5yp7m5eim
      type: object
      x-examples: {}
      description: Response for harness entities count that can be imported to IDP
      properties:
        org_count:
          type: integer
          x-stoplight:
            id: lcwk3hlcrqlse
        project_count:
          type: integer
          x-stoplight:
            id: 9iy8ubk7olrqn
        service_count:
          type: integer
      required:
        - org_count
        - project_count
        - service_count
    HarnessEntitiesResponse:
      title: HarnessEntitiesResponse
      x-stoplight:
        id: 06ugy0j5318dr
      type: object
      x-examples: {}
      description: Response for harness entities mapping with backstage entities
      properties:
        harness_backstage_entities:
          x-stoplight:
            id: xrciue3ek36e6
          type: array
          items:
            $ref: '#/components/schemas/HarnessBackstageEntities'
            x-stoplight:
              id: o4ipievo4uguh
      required:
        - harness_backstage_entities
    ImportEntitiesResponse:
      title: ImportEntitiesResponse
      x-stoplight:
        id: mbqihy6732hau
      type: object
      description: Response for import / save harness entities to IDP
      properties:
        status:
          type: string
      required:
        - status
    EntitiesForImport:
      title: EntitiesForImport
      x-stoplight:
        id: 0gdm8g08cv51p
      type: object
      description: Details of Harness Entities to import
      x-examples: {}
      properties:
        identifier:
          type: string
          minLength: 1
        entity_type:
          type: string
      required:
        - identifier
        - entity_type
    HarnessBackstageEntities:
      title: HarnessBackstageEntities
      x-stoplight:
        id: 7ox4rwh5ho9ue
      type: object
      description: Harness entities mapping with backstage entities
      properties:
        name:
          type: string
        system:
          type: string
        owner:
          type: string
        type:
          type: string
        identifier:
          type: string
        entity_type:
          type: string
      required:
        - name
        - system
        - owner
        - type
        - identifier
        - entity_type
    ConnectorDetails:
      title: ConnectorDetails
      x-stoplight:
        id: t8ug6b9zgqgup
      type: object
      properties:
        identifier:
          type: string
        type:
          type: string
          enum:
            - Github
            - Gitlab
            - Bitbucket
            - AzureRepo
      required:
        - identifier
        - type
      description: Connector details containing identifier and type
    LayoutResponse:
      title: LayoutResponse
      x-stoplight:
        id: 4120n8fn8dfkx
      type: object
    PluginInfo:
      title: PluginInfo
      x-stoplight:
        id: kpoyftiybzwns
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: 7bgn328jvn58s
        name:
          type: string
          x-stoplight:
            id: ql3oqpkls4fft
        created_by:
          type: string
          x-stoplight:
            id: l22ptpcecyfoe
        icon_url:
          type: string
          x-stoplight:
            id: 4arnqctb1wfyl
        description:
          type: string
          x-stoplight:
            id: ql3oqpkls4fft
        category:
          type: string
          x-stoplight:
            id: ql3oqpkls4fft
          enum:
            - Monitoring
            - CI/CD
            - Discovery
            - Quality
            - Security
            - Source Control Mgmt
        source:
          type: string
          x-stoplight:
            id: 4arnqctb1wfyl
        image_url:
          type: string
          x-stoplight:
            id: 93hv7yj3dpbnu
        core:
          type: boolean
          x-stoplight:
            id: m6jhd4hiady4t
        enabled:
          type: boolean
          x-stoplight:
            id: 6opetnwiiai53
      required:
        - id
        - name
        - created_by
        - icon_url
        - description
        - category
        - source
        - image_url
        - core
        - enabled
    PluginInfoResponse:
      title: PluginInfoResponse
      x-stoplight:
        id: pjaj5msyanbfi
      type: object
      properties:
        plugin:
          $ref: '#/components/schemas/PluginInfo'
          x-stoplight:
            id: ogk72ix9uoil2
      required:
        - plugin
    PluginDetailedInfoResponse:
      title: PluginDetailedInfoResponse
      x-stoplight:
        id: rp4p3xfki8wrk
      type: object
      properties:
        plugin:
          $ref: '#/components/schemas/PluginDetailedInfo'
          x-stoplight:
            id: ogk72ix9uoil3
      required:
        - plugin
    PluginDetailedInfo:
      title: PluginDetailedInfo
      x-stoplight:
        id: ggn3lgk0pl7jx
      allOf:
        - $ref: '#/components/schemas/PluginDetails'
          x-stoplight:
            id: 8r3tc7aptshub
        - type: object
          properties:
            env_variables:
              x-stoplight:
                id: 4tj9fofa4b3hn
              type: array
              items:
                $ref: '#/components/schemas/BackstageEnvSecretVariable'
                x-stoplight:
                  id: v8fluu5h3dt3n
            saved:
              type: boolean
              x-stoplight:
                id: b06clr6ww9ku0
          required:
            - env_variables
            - saved
    ManualImportEntityRequest:
      title: ManualImportEntityRequest
      x-stoplight:
        id: ssbm06g65ld8t
      type: object
      description: Details of entity to import manually to IDP
      properties:
        yaml:
          type: string
          x-stoplight:
            id: g8wygfate3kph
          description: yaml in form on json
        entity_name:
          type: string
          x-stoplight:
            id: 2axpvz6rwf0ds
      required:
        - yaml
        - entity_name
    LayoutRequest:
      title: LayoutRequest
      x-stoplight:
        id: jfyco0hsivo6b
      type: object
      description: LayoutRequest
      properties:
        name:
          type: string
          x-stoplight:
            id: zvjshp9bal6kq
        id:
          type: string
          x-stoplight:
            id: vy53h9a7l4ij3
        yaml:
          type: string
          x-stoplight:
            id: vrsrw3pv5ga85
        display_name:
          type: string
          x-stoplight:
            id: iubyqrukqnryx
        default_yaml:
          type: string
          x-stoplight:
            id: 9juzgzieo6qnl
        type:
          type: string
          x-stoplight:
            id: jb3f4rk78x16r
    AppConfig:
      title: AppConfig
      x-stoplight:
        id: lxr5mwvtpsibp
      type: object
      x-examples: {}
      properties:
        config_id:
          type: string
          x-stoplight:
            id: 4c46nx9p25z4g
        configs:
          type: string
          x-stoplight:
            id: c376cmcok0i1w
        enabled:
          type: boolean
          x-stoplight:
            id: 5k0msvhe7qhhd
        enabled_disabled_at:
          type: integer
          x-stoplight:
            id: 2kot35661my5o
          format: int64
        created:
          type: integer
          x-stoplight:
            id: 55sswchn2dgls
          format: int64
        updated:
          type: integer
          x-stoplight:
            id: gjoqaxs5xj4g5
          format: int64
        env_variables:
          type: array
          x-stoplight:
            id: rbsynehqc2icl
          items:
            $ref: '#/components/schemas/BackstageEnvSecretVariable'
            x-stoplight:
              id: h8yoj2ikr9k75
        config_name:
          type: string
          x-stoplight:
            id: jqz82xb7khx5d
      required:
        - config_id
        - configs
        - env_variables
        - config_name
    AppConfigRequest:
      title: AppConfigRequest
      x-stoplight:
        id: xohgavxbwlfjc
      type: object
      properties:
        app_config:
          $ref: '#/components/schemas/AppConfig'
          x-stoplight:
            id: mvm9nhd3eenq6
      required:
        - app_config
    AppConfigResponse:
      title: AppConfigResponse
      x-stoplight:
        id: bu5i92md2mome
      type: object
      properties:
        app_config:
          $ref: '#/components/schemas/AppConfig'
          x-stoplight:
            id: 7rhhzvrxp6grz
      required:
        - app_config
    ConnectorInfoRequest:
      title: ConnectorInfoRequest
      x-stoplight:
        id: ac9uhio4r21e5
      type: object
      properties:
        connector_details:
          $ref: '#/components/schemas/ConnectorDetails'
          x-stoplight:
            id: cfx70t6ohuzrc
    ConnectorInfoResponse:
      title: ConnectorInfoResponse
      x-stoplight:
        id: iq2fsejvdmg8g
      type: object
      properties:
        connector_details:
          $ref: '#/components/schemas/ConnectorDetails'
          x-stoplight:
            id: ictqwjgoxe2bc
      required:
        - connector_details
    Exports:
      title: Exports
      x-stoplight:
        id: qxll6vxpyv7r3
      type: object
      properties:
        pages:
          type: integer
          x-stoplight:
            id: z84hfxygvrde5
        tab_contents:
          type: integer
          x-stoplight:
            id: xsao98zphpvue
        cards:
          type: integer
          x-stoplight:
            id: ksifiqe7f9p5w
        default_entity_types:
          type: array
          x-stoplight:
            id: rubpg21bu2st4
          items:
            x-stoplight:
              id: kth23yj667xa3
            type: string
        export_details:
          x-stoplight:
            id: xszvlkfetqvdo
          type: array
          items:
            $ref: '#/components/schemas/ExportDetails'
            x-stoplight:
              id: ypu1bnoyc701c
      required:
        - pages
        - tab_contents
        - cards
        - default_entity_types
        - export_details
    MergedPluginConfigs:
      title: MergedPluginConfigs
      x-stoplight:
        id: vc33058szl2a4
      type: object
      description: Merged Config for all Enabled Plugins.
      properties:
        config:
          type: string
          x-stoplight:
            id: 9tuk5lnb9qem9
        env_variables:
          type: array
          x-stoplight:
            id: rvzbk4sw9nxvp
          items:
            $ref: '#/components/schemas/BackstageEnvSecretVariable'
            x-stoplight:
              id: lv3438bpnl1d1
      required:
        - config
        - env_variables
    MergedPluginConfigResponse:
      title: MergedPluginConfigResponse
      x-stoplight:
        id: cggq7dvi6muti
      type: object
      description: Merged Config for all Enabled Plugins Response.
      properties:
        merged_config:
          $ref: '#/components/schemas/MergedPluginConfigs'
          x-stoplight:
            id: 4cbw2qu8gjz0n
      required:
        - merged_config
    RequestPlugin:
      x-stoplight:
        id: 9hysqi3bqen2g
      type: object
      title: RequestPluginRequest
      description: Details of the plugin being requested
      properties:
        name:
          type: string
          x-stoplight:
            id: 36cfc6be33iuq
        creator:
          type: string
          x-stoplight:
            id: 1rpevk6nasps4
        package_link:
          type: string
          x-stoplight:
            id: 06dejnewki48v
        doc_link:
          type: string
          x-stoplight:
            id: kjp2dblyv5l0j
      required:
        - name
        - creator
        - package_link
        - doc_link
    PluginRequestResponseList:
      title: PluginRequestResponseList
      x-stoplight:
        id: l8pxjbva9kd77
      type: object
      properties:
        plugin_requests:
          type: array
          x-stoplight:
            id: 7p55aiahqzgfc
          items:
            $ref: '#/components/schemas/RequestPlugin'
            x-stoplight:
              id: djchso9u50p2u
      required:
        - plugin_requests
      description: Returns all plugin requests for an account
    ExportDetails:
      title: ExportDetails
      x-stoplight:
        id: dg5ogyutt74c2
      type: object
      properties:
        type:
          type: string
          x-stoplight:
            id: aurd52xhuftpn
        name:
          type: string
          x-stoplight:
            id: sq45ohcxqr9do
        add_by_default:
          type: boolean
          x-stoplight:
            id: 6tc18j0qbdoes
        default_route:
          type: string
          x-stoplight:
            id: oyrgvybpm6nik
        layout_schema_specs:
          type: object
          x-stoplight:
            id: aqq2o3sg33kiz
      required:
        - type
        - name
    PluginDetails:
      title: PluginDetails
      x-stoplight:
        id: 4rsv9twy48kan
      type: object
      properties:
        plugin_details:
          $ref: '#/components/schemas/PluginInfo'
          x-stoplight:
            id: 78o6cgyocvp5q
        config:
          type: string
          x-stoplight:
            id: knh0tubwda57c
        exports:
          $ref: '#/components/schemas/Exports'
          x-stoplight:
            id: d75z7rk3lvcbb
      required:
        - plugin_details
        - config
        - exports
    LayoutIngestRequest:
      title: LayoutIngestRequest
      x-stoplight:
        id: e8du2q55p26u5
      type: object
      properties:
        plugin:
          $ref: '#/components/schemas/PluginDetails'
          x-stoplight:
            id: jqr3z1zl2f5vs
      required:
        - plugin
  parameters:
    AccountHeader:
      name: Harness-Account
      in: header
      required: false
      schema:
        type: string
      description: 'Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.'
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
      description: 'Pagination: Number of items to return'
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
      description: "Pagination page number strategy: Specify the page number within the paginated collection related to the number of items in each page\t"
    Sort:
      name: sort
      in: query
      required: false
      schema:
        type: string
      description: Parameter on the basis of which sorting is done.
    BackstageEnvVariable:
      name: backstage-env-variable
      in: path
      required: true
      schema:
        type: string
      description: Identifier field of the backstage env variable the resource is scoped to
    StatusType:
      name: type
      in: path
      description: Status type
      required: true
      schema:
        type: string
        enum:
          - infra
          - onboarding
    AccountIdentifier:
      name: accountIdentifier
      in: path
      required: true
      schema:
        type: string
      description: Identifier field of the account the resource is scoped to
    Order:
      name: order
      in: query
      required: false
      schema:
        type: string
      description: Order on the basis of which sorting is done.
    SearchTerm:
      name: search_term
      in: query
      required: false
      schema:
        type: string
      description: This would be used to filter resources having attributes matching the search term.
    LayoutIdentifier:
      name: layout-identifier
      in: path
      required: true
      schema:
        type: string
      description: Layout Identifier
    PluginId:
      name: plugin-id
      in: path
      description: Plugin Identifier
      required: true
      schema:
        type: string
        enum:
          - pager-duty
          - snyk-security
          - harness-ci-cd
          - github-pull-requests-board
          - kafka
          - lighthouse
          - todo
    PluginName:
      name: PluginId
      in: query
      required: false
      schema:
        type: string
      description: 'Plugin name for filtering '
    Enabled:
      name: enabled
      in: query
      required: true
      schema:
        type: boolean
      description: flag for checking enablement/disablement
    ProviderType:
      name: provider-type
      in: path
      description: Provider Type
      required: true
      schema:
        type: string
  requestBodies:
    BackstageEnvVariableRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackstageEnvVariableRequest'
          examples:
            Example 1:
              value:
                env_variable:
                  identifier: 641c7f1aa18dbf72522d78f0
                  env_name: PAGERDUTY_TOKEN
                  created: 1679589047352
                  updated: 1679589047352
                  type: Secret
                  harness_secret_identifier: pdtoken
            Example 2:
              value:
                env_variable:
                  identifier: 641c7f1aa18dbf72522d78f1
                  env_name: GITHUB_APP_APPLICATION_ID
                  created: 1679589047352
                  updated: 1679589047352
                  type: Config
                  value: '1234'
        application/yaml:
          schema:
            $ref: '#/components/schemas/BackstageEnvVariableRequest'
    BackstageEnvVariableBatchRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackstageEnvVariableBatchRequest'
          examples: {}
        application/yaml:
          schema:
            $ref: '#/components/schemas/BackstageEnvVariableBatchRequest'
    BackstagePermissionsRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackstagePermissionsRequest'
          examples: {}
    StatusInfoRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusInfoRequest'
        application/yaml:
          schema:
            $ref: '#/components/schemas/StatusInfoRequest'
    ImportHarnessEntitiesRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ImportHarnessEntitiesRequest'
          examples: {}
      description: Details of Harness Entities and Catalog Location info
    ManualImportEntityRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ManualImportEntityRequest'
      description: Details of entity to import manually to IDP
    LayoutRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LayoutRequest'
    AppConfigRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppConfigRequest'
          examples:
            Example 1:
              value:
                app_config:
                  config_id: snyk-security
                  configs: |-
                    proxy:
                      '/snyk':
                        target: https://snyk.io/api/v1
                        headers:
                          User-Agent: tech-services/backstage-plugin/1.0
                          Authorization: token ${SNYK_TOKEN}
                  enabled: true
                  enabled_disabled_at: 0
                  created: 1679589146025
                  updated: 1679589146025
                  env_variables:
                    - env_name: SNYK_TOKEN
                      type: Secret
                      harness_secret_identifier: snyktoken
                  config_name: Snyk Security
    ConnectorInfoRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConnectorInfoRequest'
    RequestPluginRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RequestPlugin'
      description: Details of the plugin being requested
    LayoutIngestRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LayoutIngestRequest'
  responses:
    BackstageEnvVariableResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackstageEnvVariableResponse'
        application/yaml:
          schema:
            $ref: '#/components/schemas/BackstageEnvVariableResponse'
    BackstageEnvVariableResponseList:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BackstageEnvVariableResponse'
        application/yaml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BackstageEnvVariableResponse'
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
    BackstagePermissionsResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BackstagePermissionsResponse'
    StatusInfoResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusInfoResponse'
        application/yaml:
          schema:
            $ref: '#/components/schemas/StatusInfoResponse'
    LayoutResponse:
      description: Layout response
      content:
        text/plain:
          schema:
            $ref: '#/components/schemas/LayoutResponse'
        application/json:
          schema:
            $ref: '#/components/schemas/LayoutResponse'
    NamespaceResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NamespaceResponse'
        application/xml:
          schema:
            $ref: '#/components/schemas/NamespaceResponse'
    HarnessEntitiesResponse:
      description: Response for harness entities mapping with backstage entities
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HarnessEntitiesResponse'
          examples: {}
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
    ImportEntitiesResponse:
      description: Response for import / save harness entities to IDP
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ImportEntitiesResponse'
    PluginInfoResponseList:
      description: Example response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PluginInfoResponse'
        application/yaml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/PluginInfoResponse'
    PluginInfoResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PluginInfoResponse'
        application/yaml:
          schema:
            $ref: '#/components/schemas/PluginInfoResponse'
    PluginDetailedInfoResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PluginDetailedInfoResponse'
        application/yaml:
          schema:
            $ref: '#/components/schemas/PluginDetailedInfoResponse'
    AppConfigResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppConfigResponse'
        application/xml:
          schema:
            type: object
            properties: {}
        multipart/form-data:
          schema:
            type: object
            properties: {}
        text/html:
          schema:
            type: object
            properties: {}
    ConnectorInfoResponse:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConnectorInfoResponse'
        application/yaml:
          schema:
            $ref: '#/components/schemas/ConnectorInfoResponse'
    ConnectorInfoResponseList:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ConnectorInfoResponse'
        application/yaml:
          schema:
            $ref: '#/components/schemas/ConnectorInfoResponse'
    MergedPluginConfigResponse:
      description: Merged Config for all Enabled Plugins Response.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MergedPluginConfigResponse'
    HarnessEntitiesCountResponse:
      description: Response for harness entities count that can be imported to IDP
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HarnessEntitiesCountResponse'
    PluginRequestResponseList:
      description: Returns all plugin requests for an account
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PluginRequestResponseList'
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
tags:
  - name: AccountInfo
    description: Account Information
  - name: AppConfig
    description: Backstage App Configurations
  - name: BackstageEnvVariable
    description: Backstage Environment Variable
  - name: BackstagePermissions
    description: Backstage Permissions
  - name: ConnectorInfo
    description: Connector Information
  - name: LayoutProxy
    description: Layout Proxy
  - name: Namespace
    description: Backstage Namespace
  - name: OnboardingResource
    description: Onboarding
  - name: PluginInfo
    description: Plugin Information
  - name: Provision
    description: Provision
  - name: StatusInfo
    description: Status Information
  - name: MergedPluginsConfig
    description: Merged Plugins Configurations
